"""
Sample decks (unpacked, i.e. represented as lists of lists, for easy copying
and comparison) that can be used by test_uno.py after being re-packed by
testing_helpers.pack_deck().
"""

normal_test_deck1 = [ ['Green', '2'],
    ['Red', '5'],
    ['Yellow', 'Reverse'],
    ['Green', '0'],
    ['Yellow', '8'],
    ['Green', '+2'],
    ['Red', '9'],
    ['Green', '8'],
    ['Wild', ''],
    ['Green', '+2'],
    ['Red', '1'],
    ['Yellow', '+2'],
    ['Wild', '+4'],
    ['Yellow', '4'],
    ['Blue', '0'],
    ['Red', '2'],
    ['Blue', '7'],
    ['Blue', '1'],
    ['Blue', '1'],
    ['Green', '3'],
    ['Wild', '+4'],
    ['Blue', '7'],
    ['Blue', '8'],
    ['Wild', ''],
    ['Blue', '5'],
    ['Green', '3'],
    ['Red', '6'],
    ['Red', '6'],
    ['Wild', ''],
    ['Red', '+2'],
    ['Green', 'Skip'],
    ['Green', '9'],
    ['Red', '7'],
    ['Red', '5'],
    ['Yellow', '9'],
    ['Green', 'Skip'],
    ['Wild', ''],
    ['Green', '5'],
    ['Blue', '9'],
    ['Yellow', '9'],
    ['Yellow', '0'],
    ['Blue', 'Reverse'],
    ['Red', '0'],
    ['Wild', ''],
    ['Yellow', '4'],
    ['Yellow', 'Reverse'],
    ['Blue', '3'],
    ['Yellow', '5'],
    ['Green', '1'],
    ['Blue', '6'],
    ['Wild', '+4'],
    ['Red', 'Skip'],
    ['Yellow', '7'],
    ['Green', '9'],
    ['Red', '9'],
    ['Wild', ''],
    ['Green', '1'],
    ['Green', '6'],
    ['Red', '+2'],
    ['Yellow', '2'],
    ['Red', '7'],
    ['Blue', '4'],
    ['Green', '8'],
    ['Blue', '+2'],
    ['Yellow', '+2'],
    ['Green', '7'],
    ['Yellow', '8'],
    ['Green', '5'],
    ['Red', '4'],
    ['Yellow', '7'],
    ['Red', '8'],
    ['Blue', '3'],
    ['Blue', '6'],
    ['Yellow', '6'],
    ['Red', 'Reverse'],
    ['Red', '3'],
    ['Red', '1'],
    ['Blue', '9'],
    ['Green', '7'],
    ['Red', '3'],
    ['Blue', 'Skip'],
    ['Yellow', '2'],
    ['Green', '6'],
    ['Yellow', '1'],
    ['Blue', 'Skip'],
    ['Green', 'Reverse'],
    ['Wild', '+4'],
    ['Yellow', '1'],
    ['Blue', '4'],
    ['Blue', '+2'],
    ['Red', '2'],
    ['Blue', '8'],
    ['Red', '8'],
    ['Red', 'Reverse'],
    ['Wild', '+4'],
    ['Blue', '2'],
    ['Green', '2'],
    ['Blue', 'Reverse'],
    ['Yellow', '3'],
    ['Blue', '2'],
    ['Yellow', 'Skip'],
    ['Yellow', 'Skip'],
    ['Blue', '5'],
    ['Green', '4'],
    ['Green', '4'],
    ['Green', 'Reverse'],
    ['Yellow', '6'],
    ['Yellow', '3'],
    ['Red', 'Skip'],
    ['Wild', '+4'],
    ['Red', '4'],
    ['Yellow', '5']]

normal_test_deck2 = [ ['Red', '3'],
    ['Green', '9'],
    ['Yellow', '5'],
    ['Blue', '9'],
    ['Wild', '+4'],
    ['Wild', ''],
    ['Green', '5'],
    ['Red', 'Reverse'],
    ['Red', '1'],
    ['Yellow', '+2'],
    ['Green', '8'],
    ['Blue', 'Reverse'],
    ['Red', '8'],
    ['Blue', '7'],
    ['Wild', ''],
    ['Green', '3'],
    ['Wild', '+4'],
    ['Blue', '2'],
    ['Green', '1'],
    ['Blue', 'Skip'],
    ['Green', '4'],
    ['Yellow', '1'],
    ['Blue', '1'],
    ['Yellow', 'Reverse'],
    ['Blue', '6'],
    ['Yellow', '8'],
    ['Red', '1'],
    ['Red', '+2'],
    ['Red', '2'],
    ['Wild', '+4'],
    ['Red', '+2'],
    ['Green', 'Reverse'],
    ['Blue', '9'],
    ['Red', '0'],
    ['Red', 'Skip'],
    ['Yellow', '8'],
    ['Wild', '+4'],
    ['Blue', 'Skip'],
    ['Wild', ''],
    ['Green', '2'],
    ['Wild', '+4'],
    ['Yellow', '2'],
    ['Green', '8'],
    ['Blue', '+2'],
    ['Yellow', '+2'],
    ['Blue', '6'],
    ['Blue', '1'],
    ['Green', 'Skip'],
    ['Yellow', '4'],
    ['Blue', '+2'],
    ['Yellow', '4'],
    ['Blue', '2'],
    ['Wild', ''],
    ['Blue', '3'],
    ['Green', '2'],
    ['Red', '5'],
    ['Green', '6'],
    ['Yellow', '6'],
    ['Yellow', '7'],
    ['Yellow', '9'],
    ['Yellow', '7'],
    ['Red', '6'],
    ['Green', '0'],
    ['Yellow', '6'],
    ['Green', '+2'],
    ['Green', '5'],
    ['Red', '6'],
    ['Yellow', 'Reverse'],
    ['Green', '7'],
    ['Wild', ''],
    ['Green', '4'],
    ['Blue', '8'],
    ['Blue', '4'],
    ['Red', '7'],
    ['Green', '6'],
    ['Blue', '0'],
    ['Green', '9'],
    ['Blue', '7'],
    ['Blue', '5'],
    ['Red', '5'],
    ['Green', '7'],
    ['Red', '7'],
    ['Red', 'Skip'],
    ['Green', 'Reverse'],
    ['Yellow', '3'],
    ['Red', '4'],
    ['Green', 'Skip'],
    ['Red', '8'],
    ['Blue', '4'],
    ['Green', '3'],
    ['Blue', '8'],
    ['Blue', '5'],
    ['Red', '4'],
    ['Yellow', '0'],
    ['Yellow', '1'],
    ['Wild', ''],
    ['Red', '3'],
    ['Red', '9'],
    ['Red', 'Reverse'],
    ['Wild', '+4'],
    ['Green', '1'],
    ['Red', '9'],
    ['Yellow', '9'],
    ['Yellow', 'Skip'],
    ['Blue', '3'],
    ['Yellow', 'Skip'],
    ['Yellow', '3'],
    ['Blue', 'Reverse'],
    ['Red', '2'],
    ['Yellow', '2'],
    ['Green', '+2'],
    ['Yellow', '5']]

normal_test_deck3 = [ ['Green', '5'],
    ['Yellow', '3'],
    ['Blue', '1'],
    ['Yellow', '5'],
    ['Yellow', 'Reverse'],
    ['Red', '5'],
    ['Blue', '7'],
    ['Green', '0'],
    ['Blue', '0'],
    ['Red', '8'],
    ['Wild', '+4'],
    ['Blue', '5'],
    ['Wild', '+4'],
    ['Green', '8'],
    ['Blue', '+2'],
    ['Red', '1'],
    ['Blue', '4'],
    ['Red', '0'],
    ['Red', '2'],
    ['Green', 'Reverse'],
    ['Wild', '+4'],
    ['Green', '7'],
    ['Green', '3'],
    ['Yellow', '8'],
    ['Blue', '9'],
    ['Red', '7'],
    ['Wild', ''],
    ['Blue', '3'],
    ['Red', '4'],
    ['Yellow', '3'],
    ['Yellow', '6'],
    ['Green', 'Skip'],
    ['Blue', '3'],
    ['Green', '4'],
    ['Wild', ''],
    ['Green', '6'],
    ['Blue', '8'],
    ['Red', 'Reverse'],
    ['Red', '2'],
    ['Yellow', '2'],
    ['Blue', '9'],
    ['Red', '6'],
    ['Yellow', 'Reverse'],
    ['Green', '1'],
    ['Red', '4'],
    ['Blue', '6'],
    ['Yellow', '9'],
    ['Yellow', '4'],
    ['Blue', '+2'],
    ['Red', '9'],
    ['Green', 'Reverse'],
    ['Yellow', '6'],
    ['Blue', '4'],
    ['Wild', '+4'],
    ['Red', '5'],
    ['Yellow', '8'],
    ['Blue', '2'],
    ['Blue', 'Skip'],
    ['Blue', '7'],
    ['Red', '9'],
    ['Green', '9'],
    ['Wild', ''],
    ['Green', '5'],
    ['Wild', ''],
    ['Green', '2'],
    ['Green', '2'],
    ['Blue', 'Reverse'],
    ['Red', '8'],
    ['Red', '7'],
    ['Blue', '1'],
    ['Blue', 'Reverse'],
    ['Green', '9'],
    ['Blue', '6'],
    ['Yellow', '5'],
    ['Blue', 'Skip'],
    ['Red', '+2'],
    ['Red', '3'],
    ['Green', '8'],
    ['Yellow', '1'],
    ['Blue', '5'],
    ['Red', '6'],
    ['Green', 'Skip'],
    ['Yellow', '7'],
    ['Green', '6'],
    ['Red', '1'],
    ['Wild', ''],
    ['Yellow', '0'],
    ['Yellow', '9'],
    ['Green', '1'],
    ['Red', '3'],
    ['Red', 'Skip'],
    ['Green', '7'],
    ['Red', 'Reverse'],
    ['Red', '+2'],
    ['Yellow', '7'],
    ['Green', '4'],
    ['Wild', ''],
    ['Yellow', '+2'],
    ['Yellow', 'Skip'],
    ['Yellow', '4'],
    ['Blue', '8'],
    ['Yellow', '+2'],
    ['Green', '3'],
    ['Green', '+2'],
    ['Green', '+2'],
    ['Red', 'Skip'],
    ['Yellow', '1'],
    ['Yellow', '2'],
    ['Yellow', 'Skip'],
    ['Wild', '+4'],
    ['Wild', '+4'],
    ['Blue', '2']]

normal_test_deck4 = [ ['Red', '8'],
    ['Green', '2'],
    ['Green', '7'],
    ['Red', '7'],
    ['Wild', ''],
    ['Blue', 'Skip'],
    ['Red', 'Skip'],
    ['Red', '0'],
    ['Green', '9'],
    ['Wild', ''],
    ['Green', '6'],
    ['Wild', '+4'],
    ['Blue', '+2'],
    ['Yellow', '8'],
    ['Yellow', '3'],
    ['Blue', '8'],
    ['Blue', '+2'],
    ['Green', '7'],
    ['Wild', '+4'],
    ['Red', '6'],
    ['Red', '2'],
    ['Yellow', '5'],
    ['Red', '5'],
    ['Green', '6'],
    ['Green', 'Reverse'],
    ['Green', '4'],
    ['Yellow', '6'],
    ['Green', '5'],
    ['Green', '0'],
    ['Red', '6'],
    ['Yellow', '2'],
    ['Blue', '2'],
    ['Yellow', '6'],
    ['Yellow', 'Skip'],
    ['Wild', '+4'],
    ['Yellow', '3'],
    ['Blue', '1'],
    ['Blue', '5'],
    ['Blue', '3'],
    ['Blue', '4'],
    ['Red', '1'],
    ['Wild', ''],
    ['Red', '2'],
    ['Red', '1'],
    ['Green', 'Skip'],
    ['Green', '+2'],
    ['Blue', '1'],
    ['Green', '4'],
    ['Green', '1'],
    ['Yellow', '7'],
    ['Wild', '+4'],
    ['Blue', '4'],
    ['Red', '7'],
    ['Yellow', '9'],
    ['Blue', '2'],
    ['Yellow', '5'],
    ['Yellow', '+2'],
    ['Green', '3'],
    ['Green', '1'],
    ['Yellow', '9'],
    ['Yellow', '0'],
    ['Blue', '0'],
    ['Yellow', '7'],
    ['Blue', 'Skip'],
    ['Yellow', '4'],
    ['Green', '9'],
    ['Green', '+2'],
    ['Green', 'Skip'],
    ['Red', 'Reverse'],
    ['Blue', '6'],
    ['Red', '3'],
    ['Yellow', '2'],
    ['Red', '+2'],
    ['Wild', ''],
    ['Red', '4'],
    ['Yellow', 'Reverse'],
    ['Red', '9'],
    ['Yellow', '1'],
    ['Blue', '5'],
    ['Wild', ''],
    ['Green', '8'],
    ['Green', '8'],
    ['Red', '4'],
    ['Red', '8'],
    ['Yellow', '+2'],
    ['Blue', '7'],
    ['Blue', 'Reverse'],
    ['Yellow', '1'],
    ['Red', '3'],
    ['Red', '9'],
    ['Green', '3'],
    ['Green', '5'],
    ['Yellow', '4'],
    ['Blue', '9'],
    ['Green', '2'],
    ['Blue', 'Reverse'],
    ['Red', 'Reverse'],
    ['Red', 'Skip'],
    ['Blue', '6'],
    ['Blue', '9'],
    ['Yellow', 'Skip'],
    ['Red', '5'],
    ['Blue', '3'],
    ['Wild', ''],
    ['Wild', '+4'],
    ['Blue', '7'],
    ['Yellow', 'Reverse'],
    ['Green', 'Reverse'],
    ['Wild', '+4'],
    ['Blue', '8'],
    ['Yellow', '8'],
    ['Red', '+2']]

normal_test_deck5 = [ ['Red', '5'],
    ['Red', '5'],
    ['Blue', '1'],
    ['Green', '+2'],
    ['Green', '3'],
    ['Wild', ''],
    ['Red', '2'],
    ['Red', '6'],
    ['Green', 'Skip'],
    ['Green', 'Skip'],
    ['Yellow', 'Reverse'],
    ['Red', '3'],
    ['Yellow', '7'],
    ['Wild', ''],
    ['Green', '5'],
    ['Blue', '+2'],
    ['Red', '+2'],
    ['Red', 'Reverse'],
    ['Blue', '2'],
    ['Blue', '5'],
    ['Yellow', '3'],
    ['Red', '4'],
    ['Green', '4'],
    ['Green', '8'],
    ['Green', '+2'],
    ['Yellow', '2'],
    ['Blue', 'Reverse'],
    ['Blue', 'Skip'],
    ['Blue', '0'],
    ['Blue', '4'],
    ['Blue', 'Reverse'],
    ['Yellow', '+2'],
    ['Wild', '+4'],
    ['Green', '3'],
    ['Green', '7'],
    ['Blue', 'Skip'],
    ['Green', '2'],
    ['Yellow', '5'],
    ['Wild', '+4'],
    ['Green', '6'],
    ['Red', '3'],
    ['Green', '8'],
    ['Blue', '3'],
    ['Blue', '7'],
    ['Blue', '8'],
    ['Red', 'Skip'],
    ['Blue', '3'],
    ['Red', 'Reverse'],
    ['Red', '7'],
    ['Green', '7'],
    ['Red', '2'],
    ['Red', '0'],
    ['Red', '1'],
    ['Red', '1'],
    ['Green', '1'],
    ['Blue', '1'],
    ['Wild', ''],
    ['Blue', '9'],
    ['Green', '9'],
    ['Wild', ''],
    ['Wild', '+4'],
    ['Red', '7'],
    ['Green', '0'],
    ['Green', '6'],
    ['Yellow', '7'],
    ['Yellow', '5'],
    ['Yellow', '1'],
    ['Yellow', '4'],
    ['Yellow', '3'],
    ['Blue', '6'],
    ['Yellow', '0'],
    ['Green', '4'],
    ['Yellow', '9'],
    ['Green', 'Reverse'],
    ['Yellow', '2'],
    ['Green', '2'],
    ['Yellow', 'Skip'],
    ['Red', '6'],
    ['Green', '9'],
    ['Green', '5'],
    ['Yellow', '6'],
    ['Wild', '+4'],
    ['Red', 'Skip'],
    ['Blue', '9'],
    ['Yellow', '6'],
    ['Green', 'Reverse'],
    ['Yellow', 'Skip'],
    ['Yellow', '+2'],
    ['Yellow', '1'],
    ['Blue', '6'],
    ['Wild', '+4'],
    ['Red', '8'],
    ['Blue', '5'],
    ['Yellow', '8'],
    ['Yellow', '4'],
    ['Red', '9'],
    ['Blue', '+2'],
    ['Red', '8'],
    ['Green', '1'],
    ['Yellow', '8'],
    ['Red', '4'],
    ['Red', '+2'],
    ['Blue', '2'],
    ['Yellow', '9'],
    ['Blue', '8'],
    ['Yellow', 'Reverse'],
    ['Wild', '+4'],
    ['Wild', ''],
    ['Red', '9'],
    ['Blue', '7'],
    ['Blue', '4'],
    ['Wild', '']]

one_action_on_top_test_deck = [ ['Blue', 'Skip'],
    ['Red', '9'],
    ['Red', '1'],
    ['Yellow', '4'],
    ['Yellow', '5'],
    ['Blue', '6'],
    ['Green', '5'],
    ['Red', '2'],
    ['Blue', '+2'],
    ['Wild', '+4'],
    ['Yellow', '9'],
    ['Red', '4'],
    ['Yellow', '0'],
    ['Green', 'Skip'],
    ['Green', '6'],
    ['Wild', ''],
    ['Green', 'Reverse'],
    ['Blue', '1'],
    ['Green', '3'],
    ['Blue', '7'],
    ['Blue', '0'],
    ['Red', '3'],
    ['Green', '2'],
    ['Yellow', '2'],
    ['Green', '+2'],
    ['Red', '0'],
    ['Red', '+2'],
    ['Wild', ''],
    ['Yellow', 'Reverse'],
    ['Red', 'Reverse'],
    ['Red', '3'],
    ['Red', '7'],
    ['Wild', ''],
    ['Yellow', '+2'],
    ['Green', '3'],
    ['Yellow', '6'],
    ['Blue', '4'],
    ['Blue', '2'],
    ['Blue', '8'],
    ['Green', '7'],
    ['Blue', '9'],
    ['Green', '7'],
    ['Red', '4'],
    ['Red', '6'],
    ['Yellow', 'Reverse'],
    ['Green', '5'],
    ['Green', '2'],
    ['Red', '8'],
    ['Blue', '+2'],
    ['Yellow', 'Skip'],
    ['Green', 'Reverse'],
    ['Green', '1'],
    ['Wild', '+4'],
    ['Red', 'Skip'],
    ['Blue', '7'],
    ['Green', '0'],
    ['Wild', '+4'],
    ['Green', '6'],
    ['Blue', '6'],
    ['Yellow', '9'],
    ['Wild', ''],
    ['Blue', '5'],
    ['Green', '4'],
    ['Yellow', '4'],
    ['Red', 'Reverse'],
    ['Green', '9'],
    ['Green', 'Skip'],
    ['Green', '+2'],
    ['Red', '7'],
    ['Blue', '3'],
    ['Yellow', '3'],
    ['Yellow', '+2'],
    ['Red', '8'],
    ['Yellow', '5'],
    ['Yellow', '7'],
    ['Wild', '+4'],
    ['Green', '1'],
    ['Yellow', '1'],
    ['Red', '1'],
    ['Yellow', '3'],
    ['Blue', '4'],
    ['Yellow', '1'],
    ['Red', '9'],
    ['Red', '5'],
    ['Green', '8'],
    ['Green', '9'],
    ['Blue', 'Reverse'],
    ['Blue', '1'],
    ['Red', '5'],
    ['Wild', ''],
    ['Blue', '3'],
    ['Yellow', 'Skip'],
    ['Yellow', '6'],
    ['Wild', ''],
    ['Red', '6'],
    ['Green', '4'],
    ['Green', '8'],
    ['Blue', '8'],
    ['Red', '+2'],
    ['Blue', '5'],
    ['Yellow', '7'],
    ['Wild', '+4'],
    ['Blue', 'Reverse'],
    ['Yellow', '8'],
    ['Blue', 'Skip'],
    ['Yellow', '8'],
    ['Yellow', '2'],
    ['Blue', '9'],
    ['Wild', '+4'],
    ['Blue', '2'],
    ['Red', 'Skip'],
    ['Red', '2']]

five_actions_on_top_test_deck = [ ['Wild', ''],
    ['Red', 'Skip'],
    ['Blue', 'Reverse'],
    ['Wild', '+4'],
    ['Red', '+2'],
    ['Blue', '5'],
    ['Yellow', '6'],
    ['Blue', '+2'],
    ['Green', '1'],
    ['Yellow', '5'],
    ['Red', '9'],
    ['Green', '0'],
    ['Green', '2'],
    ['Blue', '4'],
    ['Red', '5'],
    ['Yellow', '4'],
    ['Yellow', '1'],
    ['Blue', '7'],
    ['Green', '7'],
    ['Wild', ''],
    ['Green', '8'],
    ['Blue', '3'],
    ['Green', '1'],
    ['Red', '4'],
    ['Green', '8'],
    ['Yellow', '0'],
    ['Yellow', '9'],
    ['Wild', ''],
    ['Yellow', '5'],
    ['Green', '6'],
    ['Blue', '6'],
    ['Blue', '6'],
    ['Green', '7'],
    ['Red', '7'],
    ['Yellow', 'Skip'],
    ['Blue', 'Skip'],
    ['Red', '9'],
    ['Yellow', '2'],
    ['Yellow', '2'],
    ['Green', '3'],
    ['Wild', '+4'],
    ['Red', '4'],
    ['Red', '3'],
    ['Yellow', '6'],
    ['Blue', '9'],
    ['Blue', '1'],
    ['Yellow', 'Reverse'],
    ['Blue', '7'],
    ['Blue', '3'],
    ['Blue', '+2'],
    ['Wild', ''],
    ['Yellow', '1'],
    ['Red', '6'],
    ['Green', '6'],
    ['Yellow', '7'],
    ['Yellow', '7'],
    ['Red', '0'],
    ['Green', '4'],
    ['Yellow', '8'],
    ['Blue', '5'],
    ['Yellow', '4'],
    ['Green', 'Skip'],
    ['Blue', '8'],
    ['Green', '5'],
    ['Red', '8'],
    ['Green', '9'],
    ['Yellow', '3'],
    ['Green', 'Reverse'],
    ['Green', '4'],
    ['Red', '5'],
    ['Green', '5'],
    ['Green', '3'],
    ['Blue', '1'],
    ['Green', 'Reverse'],
    ['Blue', '2'],
    ['Red', 'Reverse'],
    ['Wild', '+4'],
    ['Wild', ''],
    ['Green', '9'],
    ['Yellow', '3'],
    ['Yellow', '8'],
    ['Blue', 'Skip'],
    ['Blue', '8'],
    ['Wild', '+4'],
    ['Red', '7'],
    ['Red', '6'],
    ['Blue', '9'],
    ['Yellow', 'Reverse'],
    ['Red', 'Reverse'],
    ['Green', '+2'],
    ['Red', '1'],
    ['Yellow', 'Skip'],
    ['Blue', '4'],
    ['Blue', '0'],
    ['Red', '2'],
    ['Green', 'Skip'],
    ['Red', '3'],
    ['Red', '1'],
    ['Yellow', '+2'],
    ['Red', '+2'],
    ['Yellow', '+2'],
    ['Blue', 'Reverse'],
    ['Yellow', '9'],
    ['Wild', '+4'],
    ['Red', 'Skip'],
    ['Wild', '+4'],
    ['Wild', ''],
    ['Green', '2'],
    ['Red', '8'],
    ['Blue', '2'],
    ['Green', '+2'],
    ['Red', '2']]



unshuffled_deck = [ ['Red', '0'],  # 0
    ['Red', '1'],            # 1
    ['Red', '2'],            # 2
    ['Red', '3'],            # 3
    ['Red', '4'],            # 4
    ['Red', '5'],            # 5
    ['Red', '6'],            # 6
    ['Red', '7'],            # 7
    ['Red', '8'],            # 8
    ['Red', '9'],            # 9
    ['Red', 'Reverse'],      # 10
    ['Red', 'Skip'],         # 11
    ['Red', '+2'],           # 12
    ['Red', '1'],            # 13
    ['Red', '2'],            # 14
    ['Red', '3'],            # 15
    ['Red', '4'],            # 16
    ['Red', '5'],            # 17
    ['Red', '6'],            # 18
    ['Red', '7'],            # 19
    ['Red', '8'],            # 20
    ['Red', '9'],            # 21
    ['Red', 'Reverse'],      # 22
    ['Red', 'Skip'],         # 23
    ['Red', '+2'],           # 24
    ['Blue', '0'],           # 25
    ['Blue', '1'],           # 26
    ['Blue', '2'],           # 27
    ['Blue', '3'],           # 28
    ['Blue', '4'],           # 29
    ['Blue', '5'],           # 30
    ['Blue', '6'],           # 31
    ['Blue', '7'],           # 32
    ['Blue', '8'],           # 33
    ['Blue', '9'],           # 34
    ['Blue', 'Reverse'],     # 35
    ['Blue', 'Skip'],        # 36
    ['Blue', '+2'],          # 37
    ['Blue', '1'],           # 38
    ['Blue', '2'],           # 39
    ['Blue', '3'],           # 40
    ['Blue', '4'],           # 41
    ['Blue', '5'],           # 42
    ['Blue', '6'],           # 43
    ['Blue', '7'],           # 44
    ['Blue', '8'],           # 45
    ['Blue', '9'],           # 46
    ['Blue', 'Reverse'],     # 47
    ['Blue', 'Skip'],        # 48
    ['Blue', '+2'],          # 49
    ['Green', '0'],          # 50
    ['Green', '1'],          # 51
    ['Green', '2'],          # 52
    ['Green', '3'],          # 53
    ['Green', '4'],          # 54
    ['Green', '5'],          # 55
    ['Green', '6'],          # 56
    ['Green', '7'],          # 57
    ['Green', '8'],          # 58
    ['Green', '9'],          # 59
    ['Green', 'Reverse'],    # 60
    ['Green', 'Skip'],       # 61
    ['Green', '+2'],         # 62
    ['Green', '1'],          # 63
    ['Green', '2'],          # 64
    ['Green', '3'],          # 65
    ['Green', '4'],          # 66
    ['Green', '5'],          # 67
    ['Green', '6'],          # 68
    ['Green', '7'],          # 69
    ['Green', '8'],          # 70
    ['Green', '9'],          # 71
    ['Green', 'Reverse'],    # 72
    ['Green', 'Skip'],       # 73
    ['Green', '+2'],         # 74
    ['Yellow', '0'],         # 75
    ['Yellow', '1'],         # 76
    ['Yellow', '2'],         # 77
    ['Yellow', '3'],         # 78
    ['Yellow', '4'],         # 79
    ['Yellow', '5'],         # 80
    ['Yellow', '6'],         # 81
    ['Yellow', '7'],         # 82
    ['Yellow', '8'],         # 83
    ['Yellow', '9'],         # 84
    ['Yellow', 'Reverse'],   # 85
    ['Yellow', 'Skip'],      # 86
    ['Yellow', '+2'],        # 87
    ['Yellow', '1'],         # 88
    ['Yellow', '2'],         # 89
    ['Yellow', '3'],         # 90
    ['Yellow', '4'],         # 91
    ['Yellow', '5'],         # 92
    ['Yellow', '6'],         # 93
    ['Yellow', '7'],         # 94
    ['Yellow', '8'],         # 95
    ['Yellow', '9'],         # 96
    ['Yellow', 'Reverse'],   # 97
    ['Yellow', 'Skip'],      # 98
    ['Yellow', '+2'],        # 99
    ['Wild', ''],            # 100
    ['Wild', '+4'],          # 101
    ['Wild', ''],            # 102
    ['Wild', '+4'],          # 103
    ['Wild', ''],            # 104
    ['Wild', '+4'],          # 105
    ['Wild', ''],            # 106
    ['Wild', '+4'],          # 107
    ['Wild', ''],            # 108
    ['Wild', '+4'],          # 109
    ['Wild', ''],            # 110
    ['Wild', '+4'],          # 111
]


red_cards = [
    ['Red', '0'],
    ['Red', '1'],
    ['Red', '2'],
    ['Red', '3'],
    ['Red', '4'],
    ['Red', '5'],
    ['Red', '6'],
    ['Red', '7'],
    ['Red', '8'],
    ['Red', '9'],
    ['Red', 'Reverse'],
    ['Red', 'Skip'],
    ['Red', '+2']
]

green_cards = [
    ['Green', '0'],
    ['Green', '1'],
    ['Green', '2'],
    ['Green', '3'],
    ['Green', '4'],
    ['Green', '5'],
    ['Green', '6'],
    ['Green', '7'],
    ['Green', '8'],
    ['Green', '9'],
    ['Green', 'Reverse'],
    ['Green', 'Skip'],
    ['Green', '+2'],
]

blue_cards = [
    ['Blue', '1'],
    ['Blue', '2'],
    ['Blue', '3'],
    ['Blue', '4'],
    ['Blue', '5'],
    ['Blue', '6'],
    ['Blue', '7'],
    ['Blue', '8'],
    ['Blue', '9'],
    ['Blue', 'Reverse'],
    ['Blue', 'Skip'],
    ['Blue', '+2']
]

yellow_cards = [
    ['Yellow', '0'],
    ['Yellow', '1'],
    ['Yellow', '2'],
    ['Yellow', '3'],
    ['Yellow', '4'],
    ['Yellow', '5'],
    ['Yellow', '6'],
    ['Yellow', '7'],
    ['Yellow', '8'],
    ['Yellow', '9'],
    ['Yellow', 'Reverse'],
    ['Yellow', 'Skip'],
    ['Yellow', '+2']
]

wild_cards = [
    ['Wild', ''],
    ['Wild', '+4']
]
